name: example
description: Example use of Extended Future Builder

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.9
  extended_future_builder:
    path: ../
  cupertino_icons: ^0.1.3

flutter:
  uses-material-design: true