name: extended_future_builder
description: A FutureBuilder with some cool options
version: 0.0.2
homepage: https://github.com/ynixt/extended_future_builder

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.0.0
