name: extended_future_builder
description: A FutureBuilder with retry and separated builders for success, loading, empty and error situations.
version: 0.1.1
homepage: https://github.com/ynixt/extended_future_builder

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.8.0

flutter: